name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-profile: "minikube"
        minikube-arguments: "--memory=4096 --cpus=2 --driver=docker"

    - name: Try the Cluster
      run: kubectl get pods -A

    - name: Build Docker Image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          docker images | grep devopshint/node-app

    - name: Deploy to Minikube
      run: |
          kubectl apply -f k8s-node-app.yml

    - name: Wait for Pods to Be Ready
      run: kubectl wait --for=condition=ready pod --all --timeout=300s

    - name: Check Pods
      run: kubectl get pods -A

    - name: Describe Pods
      run: kubectl describe pods

    - name: Check Services
      run: kubectl get services -A

    - name: Describe Service
      run: kubectl describe service nodejs-app

    - name: Test Service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url

    - name: Capture Minikube Logs
      run: minikube logs --file=minikube-logs.txt

    - name: Upload Logs for Debugging
      uses: actions/upload-artifact@v3
      with:
        name: minikube-logs
        path: minikube-logs.txt
